spring.application.name=interview-ai-platform

#spring.datasource.url=jdbc:postgresql://localhost:5432/interview_ai
spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=
#spring.datasource.password=
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

server.servlet.context-path=/api/v1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

spring.ai.google.genai.api-key=${GOOGLE_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash

#spring.ai.anthropic.api-key=${ANTHROPIC_API_KEY}
#spring.ai.anthropic.chat.options.model=claude-sonnet-4-20250514

server.port=${PORT:8080}